image: registry.gitlab.com/librespacefoundation/satnogs/satnogs-network:latest

stages:
  - static
  - build
  - test
  - deploy
static_js_css:
  stage: static
  image: node
  script:
    - npm install -g eslint stylelint
    - eslint 'network/static/js/*.js'
    - stylelint 'network/static/css/*.css' 'network/static/css/*.scss'
static_python:
  stage: static
  image: python:2.7
  before_script:
    - pip install tox
  script:
    - tox -e flake8
build:
  stage: build
  image: python:2.7
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
build3:
  stage: build
  image: python:3.6
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
test:
  stage: test
  image: python:2.7
  before_script:
    - pip install tox
    - apt-get update
    - apt-get install -y ruby-sass
  script:
    - tox -e deps,pytest
docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk --update add py-pip
    - pip install docker-compose
  script:
    - CACHE_IMAGE="${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/satnogs-network:$CI_COMMIT_REF_NAME}"; export CACHE_IMAGE
    - docker-compose -f docker-compose.yml -f docker-compose.cache.yml pull cache_image || true
    - docker-compose -f docker-compose.yml -f docker-compose.cache.yml build --pull
    - |
      [ -z "$CI_REGISTRY_IMAGE" ] || {
          docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
          docker tag satnogs-network:latest $CI_REGISTRY_IMAGE/satnogs-network:$CI_COMMIT_REF_NAME
          docker push $CI_REGISTRY_IMAGE/satnogs-network:$CI_COMMIT_REF_NAME
      }
      [ -z "$DOCKERHUB_PASSWORD" ] || {
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
          docker tag satnogs-network:latest librespace/satnogs-network:$CI_COMMIT_REF_NAME
          docker push librespace/satnogs-network:$CI_COMMIT_REF_NAME
      }
  only:
    refs:
      - master
      - dev

stage:
  stage: deploy
  environment: stage
  only:
   - dev@librespacefoundation/satnogs/satnogs-network
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod -R u=rwX,o=,g= ~/.ssh/
    - echo "$SSH_SERVER_HOSTKEY" > ~/.ssh/known_hosts
    - git checkout dev
    - git push -u ssh://$SERVER_USER@$SERVER_HOST$SERVER_PATH dev

production:
  stage: deploy
  environment: production
  only:
   - master@librespacefoundation/satnogs/satnogs-network
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod -R u=rwX,o=,g= ~/.ssh/
    - echo "$SSH_SERVER_HOSTKEY" > ~/.ssh/known_hosts
    - git checkout master
    - git push -u ssh://$SERVER_USER@$SERVER_HOST$SERVER_PATH master
