image: registry.gitlab.com/librespacefoundation/satnogs/satnogs-network:latest

stages:
  - test

before_script:
  - cp env-dist .env

test:
  stage: test
  script:
    - flake8 .
    - pytest
    - eslint 'network/static/js/*.js'
    - stylelint 'network/static/css/*.css'
