image: registry.gitlab.com/librespacefoundation/satnogs/satnogs-network:latest

stages:
  - static
  - test
  - deploy
static_js_css:
  stage: static
  image: node
  script:
    - npm install -g eslint stylelint
    - eslint 'network/static/js/*.js'
    - stylelint 'network/static/css/*.css' 'network/static/css/*.scss'

test:
  stage: test
  script:
    - pip install --no-cache-dir -r requirements/dev.txt
    - cp env-dist .env
    - flake8 .
    - pytest

stage:
  stage: deploy
  environment: stage
  only:
   - dev@librespacefoundation/satnogs/satnogs-network
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod -R u=rwX,o=,g= ~/.ssh/
    - echo "$SSH_SERVER_HOSTKEY" > ~/.ssh/known_hosts
    - git checkout dev
    - git push -u ssh://$SERVER_USER@$SERVER_HOST$SERVER_PATH dev

production:
  stage: deploy
  environment: production
  only:
   - master@librespacefoundation/satnogs/satnogs-network
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod -R u=rwX,o=,g= ~/.ssh/
    - echo "$SSH_SERVER_HOSTKEY" > ~/.ssh/known_hosts
    - git checkout master
    - git push -u ssh://$SERVER_USER@$SERVER_HOST$SERVER_PATH master
