version: '3.2'
services:
  db:
    image: 'mariadb:10.4.11'
    environment:
      MYSQL_DATABASE: 'satnogsnetwork'
      MYSQL_USER: 'satnogsnetwork'
      MYSQL_PASSWORD: 'satnogsnetwork'
      MYSQL_ROOT_PASSWORD: 'toor'
  redis:
    image: 'redis:5.0.7'
  celery:
    build:
      context: '.'
    depends_on:
      - 'db'
      - 'redis'
    environment:
      PYTHONDONTWRITEBYTECODE: '1'
      DATABASE_URL: 'mysql://satnogsnetwork:satnogsnetwork@db/satnogsnetwork'
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
      CACHE_BACKEND: 'redis_cache.RedisCache'
      CACHE_CLIENT_CLASS: 'django_redis.client.DefaultClient'
      CACHE_LOCATION: 'redis://redis:6379/1'
      MEDIA_ROOT: '/var/lib/satnogs-network/media'
    command: ["djangoctl.sh", "develop_celery", "/usr/local/src/satnogs-network"]
    volumes:
      - '.:/usr/local/src/satnogs-network:z'
      - 'media:/var/lib/satnogs-network/media'
  web:
    build:
      context: '.'
    image: 'satnogs-network'
    ports:
      - '8000:8000'
    depends_on:
      - 'db'
      - 'redis'
    environment:
      PYTHONDONTWRITEBYTECODE: '1'
      DATABASE_URL: 'mysql://satnogsnetwork:satnogsnetwork@db/satnogsnetwork'
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
      CACHE_BACKEND: 'redis_cache.RedisCache'
      CACHE_CLIENT_CLASS: 'django_redis.client.DefaultClient'
      CACHE_LOCATION: 'redis://redis:6379/1'
      STATIC_ROOT: '/var/lib/satnogs-network/staticfiles'
      MEDIA_ROOT: '/var/lib/satnogs-network/media'
    command: ["djangoctl.sh", "develop", "/usr/local/src/satnogs-network"]
    volumes:
      - '.:/usr/local/src/satnogs-network:z'
      - 'static:/var/lib/satnogs-network/static'
      - 'media:/var/lib/satnogs-network/media'
volumes:
  static:
  media:
