version: '3'
services:
  db:
    image: mariadb:5.5
    environment:
    - MYSQL_DATABASE=network
    - MYSQL_USER=network
    - MYSQL_PASSWORD=network
    - MYSQL_ROOT_PASSWORD=toor
  redis:
    image: redis:3.2.8
  web:
    build:
      context: .
      dockerfile: docker/dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://network:network@db/network
    command:
      ./bin/run-docker.sh
